-- Test Data for Cloud Prosperity System
USE cloud_prosperity;
DELETE FROM bids WHERE buyer_id IN (SELECT id FROM users WHERE username LIKE 'test_%');
DELETE FROM projects WHERE user_id IN (SELECT id FROM users WHERE username LIKE 'test_%');
DELETE FROM orders WHERE buyer_id IN (SELECT id FROM users WHERE username LIKE 'test_%') OR merchant_id IN (SELECT id FROM users WHERE username LIKE 'test_%');
DELETE FROM products WHERE user_id IN (SELECT id FROM users WHERE username LIKE 'test_%');
DELETE FROM users WHERE username LIKE 'test_%';
INSERT INTO users (username, password, email, phone, role, account_type, name, real_name, address, business_scope, company_phone, company_address, is_active, created_at, updated_at) VALUES ('test_merchant1', '$2a$10$X5M7K8X5Y9Z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9', 'merchant1@example.com', '13800138001', 'user', 'merchant', 'Green Field Farm', 'Zhang Jianguo', 'Liangyuan District, Shangqiu, Henan', 'Vegetable planting, Poultry farming', '0370-1234567', '88 Lvye Road, Liangyuan District, Shangqiu', 1, NOW(), NOW());
INSERT INTO users (username, password, email, phone, role, account_type, name, real_name, address, business_scope, company_phone, company_address, is_active, created_at, updated_at) VALUES ('test_merchant2', '$2a$10$X5M7K8X5Y9Z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9', 'merchant2@example.com', '13800138002', 'user', 'merchant', 'Jinsui Agricultural Cooperative', 'Li Xiuying', 'Suiyang District, Shangqiu, Henan', 'Grain crops, Cash crops', '0370-2345678', '168 Jinsui Avenue, Suiyang District, Shangqiu', 1, NOW(), NOW());
INSERT INTO users (username, password, email, phone, role, account_type, name, real_name, address, business_scope, company_phone, company_address, is_active, created_at, updated_at) VALUES ('test_merchant3', '$2a$10$X5M7K8X5Y9Z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9', 'merchant3@example.com', '13800138003', 'user', 'merchant', 'Mountain Fruit Orchard', 'Wang Zhiqiang', 'Minquan County, Shangqiu, Henan', 'Fruit planting and picking', '0370-3456789', '56 Guoyuan Road, Shuishan Town, Minquan County', 1, NOW(), NOW());
INSERT INTO users (username, password, email, phone, role, account_type, name, real_name, address, is_active, created_at, updated_at) VALUES ('test_buyer1', '$2a$10$X5M7K8X5Y9Z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9', 'buyer1@example.com', '13900139001', 'user', 'buyer', 'Zhang San', 'Zhang San', '123 Huayuan Road, Jinshui District, Zhengzhou', 1, NOW(), NOW());
INSERT INTO users (username, password, email, phone, role, account_type, name, real_name, address, is_active, created_at, updated_at) VALUES ('test_buyer2', '$2a$10$X5M7K8X5Y9Z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9', 'buyer2@example.com', '13900139002', 'user', 'buyer', 'Li Si', 'Li Si', '456 Zhongshan Road, Longting District, Kaifeng', 1, NOW(), NOW());
INSERT INTO users (username, password, email, phone, role, account_type, name, real_name, address, is_active, created_at, updated_at) VALUES ('test_buyer3', '$2a$10$X5M7K8X5Y9Z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9', 'buyer3@example.com', '13900139003', 'user', 'buyer', 'Wang Wu', 'Wang Wu', '789 Zhongzhou Middle Road, Xigong District, Luoyang', 1, NOW(), NOW());
